const prefix = 'Thermostat';
export default {
  CURRENT_CONDITIONS_LOADED: `${prefix}.CURRENT_CONDITIONS_LOADED`,
  THRESHOLDS_LOADED: `${prefix}.THRESHOLDS_LOADED`,
  CURRENT_STATUS_LOADED: `${prefix}.CURRENT_STATUS_LOADED`,
  HEATING_THRESHOLD_UPDATED: `${prefix}.HEATING_THRESHOLD_UPDATED`,
  COOLING_THRESHOLD_UPDATED: `${prefix}.COOLING_THRESHOLD_UPDATED`,
  COOLING_OVERRIDE_UPDATED: `${prefix}.COOLING_OVERRIDE_UPDATED`,
  HEATING_OVERRIDE_UPDATED: `${prefix}.HEATING_OVERRIDE_UPDATED`,
  SYSTEM_STATUS_LOADED: `${prefix}.SYSTEM_STATUS_LOADED`,
};
