FROM node:22 as build


COPY ./package-lock.json ./
COPY ./package.json ./
RUN npm ci

COPY ./src ./src
COPY ./babel.config.js ./
COPY ./webpack.config.js ./
COPY ./tsconfig.json ./
RUN NODE_OPTIONS=--max_old_space_size=4096 npm run build

FROM nginx
COPY --from=build ./build /srv/package/thermostat_ui
COPY ./docker_nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
EXPOSE 443
